[tpch_data_pipeline.sources.filesystem.credentials]
aws_profile="cat_rnd_data"

[tpch_athena_pipeline.destination.filesystem.credentials]
region_name="af-south-1"

[tpch_athena_pipeline.destination.athena.credentials]
region_name="af-south-1"

[tpch_athena_pipeline_test.destination.filesystem.credentials]
region_name="af-south-1"

[tpch_athena_pipeline_test.destination.athena.credentials]
region_name="af-south-1"
